name: 🛂 CI/CD

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
    branches:
      - '**'

jobs:
  build:
    name: ⚗️ Lint, typecheck and format
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      FORCE_COLOR: 1
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: 🗃️ Checkout repository
        uses: actions/checkout@v4

      - name: 🏭 Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: 🛸 Setup PNPM
        uses: pnpm/action-setup@v3

      - name: 📂 Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_ENV"

      - name: 🧩 Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🧪 Lint, format and type-check
        run: pnpm turbo run lint format types

      - name: 📦 Build
        run: pnpm turbo run build:web
